# Site settings
title: 줌구's 난중(개발)일기
email: wckhg89@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: 줌구's 난중(개발)일기

# Social icons
facebook: honggu.kang.92
#linkedin: username
github: wckhg89
#deviantart: username
#codepen: username

footer: © zumgu dev blog

# Build settings
markdown: kramdown
